INSERT INTO subject(name) VALUES('Mathematics');
INSERT INTO subject(name) VALUES('Computer Science');
INSERT INTO subject(name) VALUES('English');

INSERT INTO professor(name, password, id_subject) VALUES ('John Oliver', '$2a$04$EuYk2M3WxyieHzsURxIVVu8i74PamDNJQv2x//pOIKmv0CFSVA2Uq', 1);
INSERT INTO professor(name, password, id_subject) VALUES ('Andrew Johnson', '$2a$04$EuYk2M3WxyieHzsURxIVVu8i74PamDNJQv2x//pOIKmv0CFSVA2Uq', 2);
INSERT INTO professor(name, password, id_subject) VALUES ('Mary-Anne Robinson', '$2a$04$EuYk2M3WxyieHzsURxIVVu8i74PamDNJQv2x//pOIKmv0CFSVA2Uq', 3);

INSERT INTO classs(name) VALUES ('9A');
INSERT INTO classs(name) VALUES ('10B');
INSERT INTO classs(name) VALUES ('11D');

INSERT INTO student(name, password, id_classs) VALUES ('Jim Kowitz', '$2a$04$EuYk2M3WxyieHzsURxIVVu8i74PamDNJQv2x//pOIKmv0CFSVA2Uq', 1);
INSERT INTO student(name, password, id_classs) VALUES ('Ellie Rotberg', '$2a$04$EuYk2M3WxyieHzsURxIVVu8i74PamDNJQv2x//pOIKmv0CFSVA2Uq', 1);
INSERT INTO student(name, password, id_classs) VALUES ('Stuart Benson', '$2a$04$EuYk2M3WxyieHzsURxIVVu8i74PamDNJQv2x//pOIKmv0CFSVA2Uq', 1);
INSERT INTO student(name, password, id_classs) VALUES ('Jerry Curious', '$2a$04$EuYk2M3WxyieHzsURxIVVu8i74PamDNJQv2x//pOIKmv0CFSVA2Uq', 2);
INSERT INTO student(name, password, id_classs) VALUES ('Saddie Happier', '$2a$04$EuYk2M3WxyieHzsURxIVVu8i74PamDNJQv2x//pOIKmv0CFSVA2Uq', 2);
INSERT INTO student(name, password, id_classs) VALUES ('Alex Hunter', '$2a$04$EuYk2M3WxyieHzsURxIVVu8i74PamDNJQv2x//pOIKmv0CFSVA2Uq', 2);
INSERT INTO student(name, password, id_classs) VALUES ('Fraz Sheikh', '$2a$04$EuYk2M3WxyieHzsURxIVVu8i74PamDNJQv2x//pOIKmv0CFSVA2Uq', 3);
INSERT INTO student(name, password, id_classs) VALUES ('Rob Dunham', '$2a$04$EuYk2M3WxyieHzsURxIVVu8i74PamDNJQv2x//pOIKmv0CFSVA2Uq', 3);
INSERT INTO student(name, password, id_classs) VALUES ('Tryst Toll', '$2a$04$EuYk2M3WxyieHzsURxIVVu8i74PamDNJQv2x//pOIKmv0CFSVA2Uq', 3);

INSERT INTO classs_professor(id_classs, id_professor) VALUES (1, 1);
INSERT INTO classs_professor(id_classs, id_professor) VALUES (1, 2);
INSERT INTO classs_professor(id_classs, id_professor) VALUES (1, 3);
INSERT INTO classs_professor(id_classs, id_professor) VALUES (2, 1);
INSERT INTO classs_professor(id_classs, id_professor) VALUES (2, 2);
INSERT INTO classs_professor(id_classs, id_professor) VALUES (2, 3);
INSERT INTO classs_professor(id_classs, id_professor) VALUES (3, 1);
INSERT INTO classs_professor(id_classs, id_professor) VALUES (3, 2);
INSERT INTO classs_professor(id_classs, id_professor) VALUES (3, 3);

INSERT INTO grade(grade, id_student, id_subject) VALUES ('7',1,1);
INSERT INTO grade(grade, id_student, id_subject) VALUES ('8',1,2);
INSERT INTO grade(grade, id_student, id_subject) VALUES ('9',1,3);
INSERT INTO grade(grade, id_student, id_subject) VALUES ('7',2,1);
INSERT INTO grade(grade, id_student, id_subject) VALUES ('8',2,2);
INSERT INTO grade(grade, id_student, id_subject) VALUES ('9',2,3);
INSERT INTO grade(grade, id_student, id_subject) VALUES ('7',3,1);
INSERT INTO grade(grade, id_student, id_subject) VALUES ('8',3,2);
INSERT INTO grade(grade, id_student, id_subject) VALUES ('9',3,3);
INSERT INTO grade(grade, id_student, id_subject) VALUES ('7',4,1);
INSERT INTO grade(grade, id_student, id_subject) VALUES ('8',4,2);
INSERT INTO grade(grade, id_student, id_subject) VALUES ('9',4,3);
INSERT INTO grade(grade, id_student, id_subject) VALUES ('7',5,1);
INSERT INTO grade(grade, id_student, id_subject) VALUES ('8',5,2);
INSERT INTO grade(grade, id_student, id_subject) VALUES ('9',5,3);
INSERT INTO grade(grade, id_student, id_subject) VALUES ('7',6,1);
INSERT INTO grade(grade, id_student, id_subject) VALUES ('8',6,2);
INSERT INTO grade(grade, id_student, id_subject) VALUES ('9',6,3);
INSERT INTO grade(grade, id_student, id_subject) VALUES ('7',7,1);
INSERT INTO grade(grade, id_student, id_subject) VALUES ('8',7,2);
INSERT INTO grade(grade, id_student, id_subject) VALUES ('9',7,3);
INSERT INTO grade(grade, id_student, id_subject) VALUES ('7',8,1);
INSERT INTO grade(grade, id_student, id_subject) VALUES ('8',8,2);
INSERT INTO grade(grade, id_student, id_subject) VALUES ('9',8,3);
INSERT INTO grade(grade, id_student, id_subject) VALUES ('7',9,1);
INSERT INTO grade(grade, id_student, id_subject) VALUES ('8',9,2);
INSERT INTO grade(grade, id_student, id_subject) VALUES ('9',9,3);

INSERT INTO student_subject(student_id, subject_id) VALUES (1,1);
INSERT INTO student_subject(student_id, subject_id) VALUES (1,2);
INSERT INTO student_subject(student_id, subject_id) VALUES (1,3);
INSERT INTO student_subject(student_id, subject_id) VALUES (2,1);
INSERT INTO student_subject(student_id, subject_id) VALUES (2,2);
INSERT INTO student_subject(student_id, subject_id) VALUES (2,3);
INSERT INTO student_subject(student_id, subject_id) VALUES (3,1);
INSERT INTO student_subject(student_id, subject_id) VALUES (3,2);
INSERT INTO student_subject(student_id, subject_id) VALUES (3,3);
INSERT INTO student_subject(student_id, subject_id) VALUES (4,1);
INSERT INTO student_subject(student_id, subject_id) VALUES (4,2);
INSERT INTO student_subject(student_id, subject_id) VALUES (4,3);
INSERT INTO student_subject(student_id, subject_id) VALUES (5,1);
INSERT INTO student_subject(student_id, subject_id) VALUES (5,2);
INSERT INTO student_subject(student_id, subject_id) VALUES (5,3);
INSERT INTO student_subject(student_id, subject_id) VALUES (6,1);
INSERT INTO student_subject(student_id, subject_id) VALUES (6,2);
INSERT INTO student_subject(student_id, subject_id) VALUES (6,3);
INSERT INTO student_subject(student_id, subject_id) VALUES (7,1);
INSERT INTO student_subject(student_id, subject_id) VALUES (7,2);
INSERT INTO student_subject(student_id, subject_id) VALUES (7,3);
INSERT INTO student_subject(student_id, subject_id) VALUES (8,1);
INSERT INTO student_subject(student_id, subject_id) VALUES (8,2);
INSERT INTO student_subject(student_id, subject_id) VALUES (8,3);
INSERT INTO student_subject(student_id, subject_id) VALUES (9,1);
INSERT INTO student_subject(student_id, subject_id) VALUES (9,2);
INSERT INTO student_subject(student_id, subject_id) VALUES (9,3);